/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/users": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          handle_name?: parameters["rowFilter.users.handle_name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** users */
          users?: definitions["users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          handle_name?: parameters["rowFilter.users.handle_name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          handle_name?: parameters["rowFilter.users.handle_name"];
        };
        body: {
          /** users */
          users?: definitions["users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/todos": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todos.id"];
          user_id?: parameters["rowFilter.todos.user_id"];
          title?: parameters["rowFilter.todos.title"];
          content?: parameters["rowFilter.todos.content"];
          expiration?: parameters["rowFilter.todos.expiration"];
          created_at?: parameters["rowFilter.todos.created_at"];
          updated_at?: parameters["rowFilter.todos.updated_at"];
          is_completed?: parameters["rowFilter.todos.is_completed"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["todos"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** todos */
          todos?: definitions["todos"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todos.id"];
          user_id?: parameters["rowFilter.todos.user_id"];
          title?: parameters["rowFilter.todos.title"];
          content?: parameters["rowFilter.todos.content"];
          expiration?: parameters["rowFilter.todos.expiration"];
          created_at?: parameters["rowFilter.todos.created_at"];
          updated_at?: parameters["rowFilter.todos.updated_at"];
          is_completed?: parameters["rowFilter.todos.is_completed"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todos.id"];
          user_id?: parameters["rowFilter.todos.user_id"];
          title?: parameters["rowFilter.todos.title"];
          content?: parameters["rowFilter.todos.content"];
          expiration?: parameters["rowFilter.todos.expiration"];
          created_at?: parameters["rowFilter.todos.created_at"];
          updated_at?: parameters["rowFilter.todos.updated_at"];
          is_completed?: parameters["rowFilter.todos.is_completed"];
        };
        body: {
          /** todos */
          todos?: definitions["todos"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  users: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: text */
    handle_name: string;
  };
  todos: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    user_id: string;
    /** Format: text */
    title: string;
    /** Format: text */
    content?: string;
    /** Format: timestamp without time zone */
    expiration?: string;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    updated_at?: string;
    /**
     * Format: boolean
     * @default false
     */
    is_completed: boolean;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description users */
  "body.users": definitions["users"];
  /** Format: uuid */
  "rowFilter.users.id": string;
  /** Format: text */
  "rowFilter.users.handle_name": string;
  /** @description todos */
  "body.todos": definitions["todos"];
  /** Format: uuid */
  "rowFilter.todos.id": string;
  /** Format: uuid */
  "rowFilter.todos.user_id": string;
  /** Format: text */
  "rowFilter.todos.title": string;
  /** Format: text */
  "rowFilter.todos.content": string;
  /** Format: timestamp without time zone */
  "rowFilter.todos.expiration": string;
  /** Format: timestamp without time zone */
  "rowFilter.todos.created_at": string;
  /** Format: timestamp without time zone */
  "rowFilter.todos.updated_at": string;
  /** Format: boolean */
  "rowFilter.todos.is_completed": string;
}

export interface operations {}

export interface external {}
